import { addDoc, collection, serverTimestamp } from "@firebase/firestore"
import type { NextPage } from "next"
import Head from "next/head"
import Signin from "../components/Signin"
// import Image from "next/image"
import styles from "../styles/Home.module.css"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ChatApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Signin />
    </div>
  )
}

export default Home
